### PR TITLE
[4530] Added tracking of hwaddr in PostgreSql for lease6

### PR DESCRIPTION
**Pull request by Azerothian**
http://kea.isc.org/ticket/3557

### CODE REVIEW

**Comment by tomaszmrugalski** [comment]
Thanks a lot for spending your time on this effort. I have only glanced at the changes, and they look ok, but are not sufficient. However, there are several additional steps necessary before I can start full review and merge process.

1. There are no unit-tests for this new functionality. See kea.isc.org -> Deceloper's Guide -> Contributor's Guide. If you haven't worked with unit-tests before, this may appear as an extra hassle, but it's really a long term maintainability thing. By having thorough unit-tests, we can test kea on various platforms automatically. Otherwise we'd be overwhelmed with manual testing. I'm afraid this is a hard requirement.

2. This is the first time Postgres schema is being changed, so we need to support upgrade procedure for people who deployed Kea+postgres and now upgrading. See src/bin/admin directory in general and src/bin/admin/scripts/mysql/upgrade* in particular. I'm afraid that the support for Pgsql upgrades will require a bit of work. Fortunately, it should be almost copy-paste from its mysql equivalent. You may want to read section 4 (and 4.1 in particular) of Kea User's Guide.

3. Your patch covers storage of MAC address, but there are two other parameters that may be very useful: hwaddress type and hw address source. While this is strictly not required, it would be very useful to cover those as well. If you're not interested in implementing this field at all, please at least add them to the schema. We can work out the code later without enforcing users to go through the hassles of another database upgrade.

4. You used BYTEA type, which allows flexible size of data. I vaguely remember a guidance that using fixed size fields is preferred for performance reasons. Would it be better to use fixed format? I used varchar(20) for MySQL. 20 is the longest hardware address that I'm aware of (it's from an architecture called Infiniband). I'm no SQL expert by any means, so feel free to ignore this comment. If you're curious about performance, there's perfdhcp tool in src/bin/perfdhcp that can be used to test whether there are any noticeable changes.

Thanks again for contributting to kea. I look forward to hear from you soon and to your updated patch.

**Comment by tomaszmrugalski** [comment]
We have not forgotten about this request, but it seems we will likely not be able to get round to it in upcoming Kea 1.1. There are two tickets related to this patch: 3557 and 4530.

**Comment by tomaszmrugalski** [comment]
We're going through ticket clean up right now. The origincal 3557 has been closed (add hwaddr fields), but we still have this one open: http://kea.isc.org/ticket/4530

**Comment by tmarkwalder** [comment]
Tomasz comment on 2016-09-07 is accurate, the schema changes adding the following three fields has been done under [3557]:

hwaddr text,
hwtype smallint,
hwaddr_source text

render this patch somewhat obsolete.  We do still have the outstanding work described in 4530 to actually read and write the values to and from the database as per 4530.   I would recommend we add this to the 1.3 milestone.

**Comment by tomaszmrugalski** [comment]
The last missing piece of code originally proposed in this PR has now been implemented and merged in #70. Closing.

@Azerothian, thanks for submitting this patch back in the early days.
@razvan-becheriu, thanks for implementing it in 2018 :)

**Pull request closed without merging**
