### PR TITLE
log: fix compilation error for LogLevelString func and compatibility for cross-compile (#ticket 3745)

### PR DESCRIPTION
**Pull request by hbl0307106015**
The log4cplus 2.0.x API is changed, PR can fix the compilation error.

`
logger_level_impl.cc: In static member function 'static void isc::log::LoggerLevelImpl::init()':
logger_level_impl.cc:205:65: error: invalid conversion from 'isc::log::LoggerLevelImpl::LogLevelString (*)(log4cplus::LogLevel) {aka std::__cxx11::basic_string<char> (*)(int)}' to 'log4cplus::LogLevelToStringMethod {aka const std::__cxx11::basic_string<char>& (*)(int)}' [-fpermissive]
     manager.pushToStringMethod(LoggerLevelImpl::logLevelToString);
                                                                 ^
In file included from /home/banglang/work/ramips/staging_dir/target-mips_24kc_glibc/usr/include/log4cplus/logger.h:34:0,
                 from logger_level_impl.cc:12:
/home/banglang/work-2nd/ramips/staging_dir/target-mips_24kc_glibc/usr/include/log4cplus/loglevel.h:160:14: note:   initializing argument 1 of 'void log4cplus::LogLevelManager::pushToStringMethod(log4cplus::LogLevelToStringMethod)'
         void pushToStringMethod(LogLevelToStringMethod newToString);
              ^
Makefile:675: recipe for target 'libkea_log_la-logger_level_impl.lo' failed
`

Signed-off-by: BangLang Huang <banglang.huang@foxmail.com>

### CODE REVIEW

**Comment by fxdupont** [comment]
What is your log4cplus version and if it is from a standard package the system and package names?

**Comment by hbl0307106015** [comment]
@fxdupont  my log4cplus version is 653e0617365eba286769aa19f7faa09402936b47
 the git HEAD from 2.0.x branch
 see https://github.com/log4cplus/log4cplus/commits/2.0.x

And I am porting kea package into LEDE/OpenWRT.
https://github.com/lede-project/source, 
The target kea-msg-compiler build failed as well when cross-compile, it seems the kea project can not support cross-compile (when build image for mips, arm on x86 machine...)

**Comment by fxdupont** [comment]
I created a ticket which was adopted for Kea 1.4 (next release after the 1.3 at the end of the month).
BTW you should add a #if for version >= 2.0.0 (there are a few for auto_ptr vs unique_ptr) and you may not return a reference to a local temporary value... I can push the branch on GitHub if you need it.

**Comment by hbl0307106015** [comment]
OK, Thanks, could you tell me which version of the log4cplus does the kea project (v1.3)  base on ?

**Comment by fxdupont** [comment]
Current Kea 1.3 code should work with 2.0.0-rc1 but not with 2.0.0-rc2. According to git the change which was not (yet) taken into account is:
commit d495e4e7b0565afb18c1114a80332a053eee68ca
Author: Vaclav Haisman <vhaisman@gmail.com>
Date:   Mon Mar 20 23:48:20 2017 +0100
(it removes compatibility with 1.0.x versions).
BTW do you know when 2.0.0 will be released? If it will be soon enough I can try to convince my colleagues of pushing the update to Kea 1.3 before it is released.

**Comment by hbl0307106015** [comment]
Sorry, I don't know when 2.0.0 will be released.

**Comment by hbl0307106015** [comment]
@fxdupont  I updated my commit, please check it again. :-) thanks

**Comment by fxdupont** [comment]
I've just merge Kea 5380 with basic patch. Please close the PR if it is enough.

**Pull request closed without merging**
