### PR TITLE
Update asiolink for boost 1.87

### PR DESCRIPTION
**Pull request by q66**
i'm going through boost 1.87 update in chimera linux and kea was one of the things failing to build due to removal of deprecated api from asio, so here are fixes

### CODE REVIEW

**Review by fxdupont — COMMENTED** [review]
If it works it should be better to include the asiolink/io_service.h file in iface_mgr.cc.

BTW I am afraid that some unit test and hook file need update too.

**Comment by q66** [comment]
hm, i'm not sure what that means?

**Comment by fxdupont** [comment]
Integrated into Kea gitlab issue 3696 which should be very likely in the next release 2.7.6 at the end of January 2025.

**Comment by andrei-pavel** [comment]
@q66, would you like to be commended in the AUTHORS file for this contribution? And if so, should it be under name `q66`?

**Comment by fxdupont** [comment]
Or in the ChangeLog entry? In anycase your name is needed...

**Comment by q66** [comment]
i don't really mind either way but if you do, yes that's fine

**Comment by fxdupont** [comment]
We need a qualified identity (of any type e.g. full name, email, url, etc) for citing you as a contributor.

**Comment by tomaszmrugalski** [comment]
> We need a qualified identity (of any type e.g. full name, email, url, etc) for citing you as a contributor.

Not really. `q66` would be probably the shortest attribution and most cryptic so far, but I will do.

Thanks for the patch!

**Pull request merged**
