### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**

### CODE REVIEW

**Comment by vrisk** [comment]
Thank you for spell-checking Kea!

**Comment by tomaszmrugalski** [comment]
I have reviewed your patch and it looks good. I'll merge it to master in couple minutes. @jsoref How would you like to be credited for it? Would "Josh Soref" be ok or do you prefer anything else added? Maybe company name or an email?

**Comment by tomaszmrugalski** [comment]
Ok, the changes are now on master. 3 changes had to be reverted. One is an intentional spelling mistake in unit-tests and two others are generated by bison, so the changes will be reverted the next time we touch anything in parsers.

Other than that, the code is now on our internal master. They should be pushed to github in an hour or so. Thanks a lot for your patch. 

@jsoref can you take a look at ChangeLog and AUTHORS and see if the acknowledgements are ok? If they're not, please reopen this PR.

**Comment by jsoref** [comment]
@tomaszmrugalski:
1. "Josh Soref" is fine (this was done on a weekend outside of company time, we do use isc-dhcp-server, so it's sort of a forward looking thing). There's no point in including an email address, they're fairly fleeting. I'm pretty reachable.

2. Do you happen to have a pointer for your upstream bison? I'm happy to spellcheck them too. (I've certainly used it often enough, although the most recent direct use of it was probably in university...).

**Comment by fxdupont** [comment]
Josh Soref writes:
> 2. Do you happen to have a pointer for your upstream bison?

https://www.gnu.org/software/bison/

The skeleton for generated files is data/lalr1.cc

Regards

Francis Dupont <fdupont@isc.org>

**Comment by jsoref** [comment]
Submitted via their ml as part of https://github.com/jsoref/bison/commit/4be8a9bca2b804587ba6ae8928fdca4da07b2869

**Pull request closed without merging**
