### PR TITLE
perfdhcp with late-exit-delay + documentation fix

### PR DESCRIPTION
**Pull request by andreipavelQ**
- perfdhcp -m \<delay\> waits for \<delay\> us after an exit condition has been met to receive all packets without sending any new packets.
- documentation: "Use -D0 to abort if even a single request has been dropped.". -D0 is not allowed, -D1 achieves that.

Disclaimer:  late-exit-delay mode shouldn't be used for an actual measuring, but maybe for a preliminary setup network assessment to see if packets get lost in the network or do actually arrive in perfdhcp after it would have normally ended. I understand this makes it a controversial change. We felt the need for it and now we are sharing. If you do reject late-exit-delay, do consider the documentation fix.

### CODE REVIEW

**Comment by tmarkwalder** [comment]
Why is this useful to you?   If you could explain what you use this for it would help
us evaluate its utility.

---

The name "late-exit-delay" implies a more intricate thing than what it really means.
"exit-wait-time" is clearer and would allow command line option of "W" for "wait"

---

An explanation of the option needs to be added to usage()

---

Is it really useful to specify the delay value in microseconds? I should think
seconds would suffice and be more user friendly.

---

Commentary for haveAllPacketsBeenReceived() in test_control.h is a copy of 
the commentary for lateExit().

---

Seems like haveAllPacketsBeenReceieved() should set request_count_RA_RR to 0
when num_request_size < 2 rather than num_request[0].

Ultimately, couldn't you simply the logic to do this?
`
   :

    uint32_t responses = 0;
    unit32_t requests = num_request[0];
    if (num_request_size >= 2) {
        requests += num_request[1];
    }

    if (ipversion == 4) {
        responses = stats_mgr4_->getRcvdPacketsNum(StatsMgr4::XCHG_DO) +
                    stats_mgr4_->getRcvdPacketsNum(StatsMgr4::XCHG_RA);
    }
        responses = stats_mgr6_->getRcvdPacketsNum(StatsMgr6::XCHG_SA) +
                    stats_mgr6_->getRcvdPacketsNum(StatsMgr6::XCHG_RR);
    }

    return (responses == requests);
}
`
---

Rename lateExit() to waitToExit() which returns true if we are not ready to exit
(i.e. must continue to wait).

That way the invoking code would read like this:
`
    if (max_pdrops) {
        if (testDiags('e')) {
            std::cout << "Reached maximum percentage of drops." << std::endl;
        }

        if (!waitToExit()) {
            return (true);
        }
    }
`

The function, waitToExit(), would then be reorganized as follows:  

`
bool
TestControl::waitToExit() const {
    static ptime exit_time = ptime(not_a_date_time);
    uint32_t wait_time = options.getExitWaitTime();

    // If we care and not all packets are in yet
    if (wait_time && !haveAllPacketsBeenReceived()) {
        const ptime now = microsec_clock::universal_time();

        // Init the end time if it hasn't started yet
        if (exit_time.is_not_a_date_time()) {
            CommandOptions& options = CommandOptions::instance();
            exit_time = now + time_duration(microseconds(wait_time);
        }

        // If we're not at end time yet, return true
        return (now < exit_time);
    }

    // No need to wait, return false;
    return (false);
}
`

**Comment by tmarkwalder** [comment]
Why is this useful to you?   If you could explain what you use this for it would help
us evaluate its utility.

---

The name "late-exit-delay" implies a more intricate thing than what it really means.
"exit-wait-time" is clearer and would allow command line option of "W" for "wait"

---

An explanation of the option needs to be added to usage()

---

Is it really useful to specify the delay value in microseconds? I should think
seconds would suffice and be more user friendly.

---

Commentary for haveAllPacketsBeenReceived() in test_control.h is a copy of 
the commentary for lateExit().

---

Seems like haveAllPacketsBeenReceieved() should set request_count_RA_RR to 0
when num_request_size < 2 rather than num_request[0].

Ultimately, couldn't you simply the logic to do this?

```c++
    uint32_t responses = 0;
    unit32_t requests = num_request[0];
    if (num_request_size >= 2) {
        requests += num_request[1];
    }

    if (ipversion == 4) {
        responses = stats_mgr4_->getRcvdPacketsNum(StatsMgr4::XCHG_DO) +
                    stats_mgr4_->getRcvdPacketsNum(StatsMgr4::XCHG_RA);
    }
        responses = stats_mgr6_->getRcvdPacketsNum(StatsMgr6::XCHG_SA) +
                    stats_mgr6_->getRcvdPacketsNum(StatsMgr6::XCHG_RR);
    }

    return (responses == requests);
}
```

---

Rename lateExit() to waitToExit() which returns true if we are not ready to exit
(i.e. must continue to wait).

That way the invoking code would read like this:

```c++
    if (max_pdrops) {
        if (testDiags('e')) {
            std::cout << "Reached maximum percentage of drops." << std::endl;
        }

        if (!waitToExit()) {
            return (true);
        }
    }
```

The function, waitToExit(), could be reorganized as follows:  

```c++
bool
TestControl::waitToExit() const {
    static ptime exit_time = ptime(not_a_date_time);
    uint32_t wait_time = options.getExitWaitTime();

    // If we care and not all packets are in yet
    if (wait_time && !haveAllPacketsBeenReceived()) {
        const ptime now = microsec_clock::universal_time();

        // Init the end time if it hasn't started yet
        if (exit_time.is_not_a_date_time()) {
            CommandOptions& options = CommandOptions::instance();
            exit_time = now + time_duration(microseconds(wait_time);
        }

        // If we're not at end time yet, return true
        return (now < exit_time);
    }

    // No need to wait, return false;
    return (false);
}
```

**Comment by razvan-becheriu** [comment]
Hi,

The changes seem OK.
One thing though, in the refactoring of the function:

bool
TestControl::waitToExit() const {
    static ptime exit_time = ptime(not_a_date_time);
   CommandOptions& options = CommandOptions::instance();
    uint32_t wait_time = options.getExitWaitTime();

    // If we care and not all packets are in yet
    if (wait_time && !haveAllPacketsBeenReceived()) {
        const ptime now = microsec_clock::universal_time();
        // Init the end time if it hasn't started yet
        if (exit_time.is_not_a_date_time()) {
            exit_time = now + time_duration(microseconds(wait_time);
        }

        // If we're not at end time yet, return true
        return (now < exit_time);
    }

    // No need to wait, return false;
    return (false);
}

The code did not compile, as the options variable has not been defined. :)

**Comment by tomaszmrugalski** [comment]
Razvan, Thomas, thanks for your reviews and comments.

I did apply the changes as suggested and updated the man page (that seems to not be updated).

The code is now merged to our internal master and should pop up on github in an hour or so.

Thanks for another patch. Closing.

**Pull request closed without merging**
