### PR TITLE
C++11 fixes

### PR DESCRIPTION
**Pull request by shane-kerr**
_Sorry for the duplicate pull request. I closed it because of the size, but decided to re-open it. Apparently in GitHub you can't open a closed PR. That sucks, but oh well._

I needed a few fixes to build this on my Arch Linux system on a Freescale CPU. I think these are related to my choice to get log4cplus 2.x, which seems to require C++11.

The changes are basically that in one place log4cplus uses `unique_ptr` instead of `auto_ptr`, and that the behavior or `make_pair()` was changed to do some type magic which breaks the usage in the code.

I couldn't get gtest to work, so I don't really know if this does the right thing, but it seems like a straightforward transition. I don't know how new `unique_ptr` is, so if you want support for old compilers then it may require some autoconf voodoo.

Sorry the PR is so big. I based my work off of the Kea git at ISC, which doesn't appear to have been synchronized in a month or so. Maybe you can cherry-pick the actual commit: f489695bd939e38452eea660bd3df6348e958a2c

### CODE REVIEW

**Comment by sodabrew** [comment]
You can use `git rebase` to get just your one commit on a branch by itself that is branched from the current master commit. More than happy to help explain how to get your pretty small set of changes separated out from this mess of merges.

**Comment by shane-kerr** [comment]
Sorry, I don't have a lot of interesting in spending time cleaning this PR up. I'm not a Kea developer and just pushed upstream changes that I needed to get it to build.

As I said in the original pull request, the reason it is so big is that ISC had a lot of changes in their git repository which are not on GitHub. For some reason they don't keep the two locations synchronized.

I rebase periodically ... usually whenever I update my server I'll rebase from master and push the changes, which updates this pull request. You can see those in the changelog here.

As I said in the initial pull request, the actual changes are in f489695bd939e38452eea660bd3df6348e958a2c if you want to use them. I have a second commit in 16f6d70d4679154080a6cf63210cb42fc4efc6ba that I made later as the latest gcc also deprecates `auto_ptr` completely.

Good luck!

**Comment by fxdupont** [comment]
kea 1.2 moved to C++11 so IMHO you can close this PR.

**Comment by shane-kerr** [comment]
Based on Francis' feedback, this appears to be no longer necessary.

**Pull request closed without merging**
