### PR TITLE
google benchmark support (with lease manager and HDS)

### PR DESCRIPTION
**Pull request by andreipavelQ**
Some test that we used for benchmarking included as part of the generic HDS unittest. It does a bunch of inserts followed by select statements, all timed and repeated on a increasingly number of hosts and. DISABLED_ by default.

### CODE REVIEW

**Comment by tomaszmrugalski** [comment]
Let's start with the biggest comment that will probably be most tricky to
handle: the license. All the files you submitted mention Apache license, while
Kea is distributed under Mozilla license (MPL2.0). Would it be possible for you to 
reconsider and change the license to Mozilla?

Yes, we previously accepted code for Cassandra under Apache license, but we did
as an exception rather than a rule. The Cassandra case is somewhat different. It
is not compiled by default, so people who expect to get the code under Mozilla
license can simply not compile Cassandra. Also, having the code under two
licenses is generally very bad for system packagers. We already had complaints
about the licensing being unclear (iirc they were coming from Debian, but also
from customers). 

If you are afraid that ISC would do something stupid with the code (like become
greedy, close the source and start selling it for $$$), that's not gonna
happen. When we receive a patch, we are bound by the license of that patch. As
such, we can only continue distributing it under the license we got it under.

-------------------

Initially I reported there are issues with the missing regex libraries in
benchmark. I haven't figured out what exactly was the root cause of the problem,
but I couldn't make the --with-benchmark-source option to work.

The workaround for this problem was to build and install (make install)
benchmark and then use --with-benchmark. This works well.

Just for completeness, here's the problem I encountered when using
--with-benchmark-source. I downloaded benchmark 1.3.0, used cmake to generate
the makefiles, then built it, then pointed to it using
--with-benchmark-source. Then, when I tried to compile Kea sources I got this:

```
make[3]: Entering directory '/mnt/ssd1/devel/kea/ext/benchmark'
Making all in .
make[4]: Entering directory '/mnt/ssd1/devel/kea/ext/benchmark'
  CXX      libbenchmark_a-benchmark.o
In file included from benchmark.cc:44:0:
/home/thomson/devel/benchmark-1.3.0/src/re.h:34:2: error: #error No regular expression backend was found!
 #error No regular expression backend was found!
  ^~~~~
/home/thomson/devel/benchmark-1.3.0/src/re.h:67:2: error: #error No regular expression backend implementation available
 #error No regular expression backend implementation available
  ^~~~~
/home/thomson/devel/benchmark-1.3.0/src/re.h: In member function 'bool benchmark::Regex::Init(const string&, std::__cxx11::string*)':
/home/thomson/devel/benchmark-1.3.0/src/re.h:102:21: error: 're_' was not declared in this scope
   int ec = regcomp(&re_, spec.c_str(), REG_EXTENDED | REG_NOSUB);
                     ^~~
/home/thomson/devel/benchmark-1.3.0/src/re.h:102:40: error: 'REG_EXTENDED' was not declared in this scope
   int ec = regcomp(&re_, spec.c_str(), REG_EXTENDED | REG_NOSUB);
                                        ^~~~~~~~~~~~
/home/thomson/devel/benchmark-1.3.0/src/re.h:102:55: error: 'REG_NOSUB' was not declared in this scope
   int ec = regcomp(&re_, spec.c_str(), REG_EXTENDED | REG_NOSUB);
                                                       ^~~~~~~~~
/home/thomson/devel/benchmark-1.3.0/src/re.h:102:64: error: 'regcomp' was not declared in this scope
   int ec = regcomp(&re_, spec.c_str(), REG_EXTENDED | REG_NOSUB);
                                                                ^
/home/thomson/devel/benchmark-1.3.0/src/re.h:105:52: error: 'regerror' was not declared in this scope
       size_t needed = regerror(ec, &re_, nullptr, 0);
                                                    ^
/home/thomson/devel/benchmark-1.3.0/src/re.h: In destructor 'benchmark::Regex::~Regex()':
/home/thomson/devel/benchmark-1.3.0/src/re.h:126:14: error: 're_' was not declared in this scope
     regfree(&re_);
              ^~~
/home/thomson/devel/benchmark-1.3.0/src/re.h:126:17: error: 'regfree' was not declared in this scope
     regfree(&re_);
                 ^
/home/thomson/devel/benchmark-1.3.0/src/re.h: In member function 'bool benchmark::Regex::Match(const string&)':
/home/thomson/devel/benchmark-1.3.0/src/re.h:134:19: error: 're_' was not declared in this scope
   return regexec(&re_, str.c_str(), 0, nullptr, 0) == 0;
                   ^~~
/home/thomson/devel/benchmark-1.3.0/src/re.h:134:50: error: 'regexec' was not declared in this scope
   return regexec(&re_, str.c_str(), 0, nullptr, 0) == 0;
                                                  ^
Makefile:490: recipe for target 'libbenchmark_a-benchmark.o' failed
make[4]: *** [libbenchmark_a-benchmark.o] Error 1

```

For the time being we can simply assume the --with-benchmark-source doesn't
work. That's perfectly ok for now. The only reason such an option exists for gtest
(--with-gtest-source) is because a long time ago Google was pushing very hard to
not install gtest at all and use it in the source form. That's the historic
background for having --with-gtest and --with-gtest-source.

Google doesn't have the same reservation in benchmark. As such, benchmark can be
handled with normal installation. So the question is whether the
--with-benchmark-source is really needed? If not, I suggest removing it.

----------

There's a warning during configure that benchmark-config was not found. I
couldn't find this tool in benchmark sources. I tried to use latest git and also
1.3.0 release. This warning doesn't seem to affect anything. I was just curious where
did you get this bnechmark-config tool from. I didn't touch the configure.ac as I'm
really barely started understanding what's going on with benchmark.

The following warning is printed during configure:

```
configure: WARNING: Unable to locate Google Benchmark benchmark-config.
```
-----------------------

Am afraid the code need some more work before it could be merged. The
major deficiencies are:

1. there are no doxygen comments whatsoever. Our coding guidelines are clear in
that regard: every class, method, function and parameter has to be
documented. This is especially important in cases like this.  Majority (maybe
even all) of the developers who don't have any experience with google
benchmark. They will look at the code and will try to figure out how the code
works and what the framework can and cannot do.

2. the method names don't follow the guidelines. One particularly bad
file in that regard is generic_host_data_source_benchmark.h. We use camel
notation for method names (e.g. get6SubnetIdAddress() rather than
get6_2_subnetid_address()). It is probably not stated clearly in the coding
guidelines, but the method should be somewhat descriptive if possible.
An example of bad name is get4_4(). Such name doesn't explain what the method
does at all. Much better name would be getLease4ByIdentifier.

3. Code wrapping. The code in general should be wrapped to 80 columns, but it's
ok to go up to 100 cholumns. The parameters should be continued in the same
line until the upper 100 cols limit is reached. C++ names tends to be longer,
so sometimes this is a bit awkward, but we try to follow that general principle.

4. Docs. There was simply no documentation written at all for the benchmarks.
For ISC developers (and possibly other advanced users out there) having some
kind of docs is essential. It's a difference between "let me take a look at
this, maybe I'll contribute something" and "I don't have time to figuring out
how to use it at all, so let's ignore it". Yes, I know that writing docs
is sometimes boring, but this is the price we need to pay. For a long
sustainability of the project, the code must be reasonably easy to understand
for new developers.

Regarding docs I think there are two major aspects here. First, we need an overview of the
benchmark concept, how to compile and run it, how to interpret the results
and how to develop new benchmarks. I wrote a first attempt for this. See
benchmarks.dox on github36 branch. Please pull and review and possibly
improve it. I don't claim to be an expert in the matter, so there may be some
obvious mistakes. Second, the generic base classes are also essential to
understand how the benchmarks are run and sadly those are completely lacking
any sort of comments. We don't need trivial comments like stating that a constructor
is a constructor, but rather an overview comments. There should be a class comment
that explains general control flow, how to use this class, when the SetUp4
and SetUp6 are called (and why they're reentrant), whether the code be
called in a single thread or many (the "reentrant" in the name and the
information printed during runtime about 8 CPUs suggests there's parallelism
involved), what the derived classes are expected to provide etc.

There are many benchmarks defined, but it is difficult to understand what they
do. As a learning exercise I wrote several tests for memfile lease backend.
See the memfile_lease_mgr_benchmark.cc on github36 branch. It is far from being
complete, but at least it should give you some idea what sort of comments
we should have.

For unit tests, we have a practice of having at least a line of comment that
explains what the test is trying to do. We've sometimes done a poor job with it,
but the general concept is to explain why this specific test was developed and
what is its goal. I think similar concept could be extended to benchmarks.

----
**generic_lease_mgr_benchmark.h**

The methods for basic operations were renamed to use bench prefix. I
wanted to explain in the developer's guide what are the method in
generic classes that are benchmarkable. I came up with an idea that
tests defined in generic classes have test* prefix, so we could name
methods in here bench*.

------------------
When I ran all benchmarks together, I got the following error:

```
MySqlHostDataSourceBenchmark/insertHosts/512                            517461 us      88348 us          8
MySqlHostDataSourceBenchmark/insertHosts/4096                          3767680 us     681275 us          1
MySqlHostDataSourceBenchmark/insertHosts/32768                        32915364 us    5585348 us          1
MySqlHostDataSourceBenchmark/insertHosts/65533                        66514236 us   11000870 us          1
terminate called after throwing an instance of 'isc::dhcp::DuplicateEntry'
  what():  Database duplicate entry error
Aborted.

real	215m19,408s
user	3m48,172s
sys	2m33,092s

```
However, running the benchmark on its own (./run-benchmarks
--benchmark_filter=MySqlHostDataSourceBenchmark/insertHosts/65533)
didn't show the problem. It must be a leftover from earlier tests.

I haven't found out what the cause of this problem was.

-----------------------------

There are many aspects here. Let's discuss what the next steps should
be here. If you want to take a look at my changes, I pushed them to
github36 branch.

**Comment by razvan-becheriu** [comment]
Hi,

It seems that the error:
'#error No regular expression backend was found!'
is related to the fact that the google benchmark library is compiled using cmake, and the cmake build environment uses compilation flags which are not exported to a header file like the "config.h" in the autotools and configure build.

To make the source compile with --with-benchmark-source=/path_to_google_benchmarks/
just add the CPPFLAGS with the value automatically configured in the '/path_to_google_benchmarks/build/test/CMakeFiles/benchmark_test.dir/flags.make' 
when configuring the kea build

eg:
./configure --prefix=/opt/dt-kea --enable-generate-parser --with-werror --with-benchmark-source=/path_to_google_benchmarks CPPFLAGS='-DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -DHAVE_STEADY_CLOCK -DTEST_BENCHMARK_LIBRARY_HAS_NO_ASSERTIONS'

Regards,
Razvan

**Comment by razvan-becheriu** [comment]
Some comments on the documentation:
src/lib/dhcpsrv/benchmarks/benchmarks.dox

@todo: We should explain how the benchmarks are actually run, what does the state
parameter passed actually represent, why the setup code needs to be reentrant etc.

I have attached to the 'run-benchmarks' process and it seems that the implementation is currently single threaded.

The functions called reentrant do not relate in any way to the parallel processing paradigm.
The naming just suggests that they are self sufficient, meaning that it does not matter what data is present in the database, everything will be cleared before the test and will be populated with the necessary data when running the test.
This also implies that you can stop the test at any time, and subsequent tests will not be affected by this action.

You can rename the functions as you like, to resolve this misunderstanding.

**Comment by tomaszmrugalski** [comment]
After spending several days improving and fixing the code, it has been finally merged today. There was substantial amount of work (the original diff @razvan-becheriu submitted was 2.4k lines, the changes I did after #issuecomment-359978525 was over 4.8k lines.

The changes are not substantial, there's just a lot of things that had to be done: duplicated code removed, comments added, parameters described, documentation written, methods renamed to be descriptive (how anyone could guest what get6_4() supposed to do?) and follow Kea coding guidelines, code wrapped etc. I understand that these kind of changes may not be the most exciting things to do, but in the future we will not accept patches that require to much of such obvious fixes.

The code is now merged on our internal master. The commits should pop up on github in an hour or so. Thanks for contributing those patches. Closing.

**Comment by razvan-becheriu** [comment]
‎Hi,Sorry for the inconvenient situation. ‎I am currently working at other things and did not have time to contribute more at this PR. I do not wish to cause you or anybody else this kind of trouble.I've suggested that this PR is not that important and that there are several other things more relevant to be handled, like all the tickets you have opened and I agree they must be handled or the list of features you have planned for 1.4 release (HA).I will try to do better in the feature. And if there comes a time with a similar situation, just mention (like you already have) what needs to be done and I will handle the changes when I have time.Thanks a lot for the effort! and once again,‎ sorry for the inconvenience.Best regards,Razvan                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Orange network.                                                                                                                                                                                                                From: Tomek MrugalskiSent: Wednesday, February 14, 2018 01:10To: isc-projects/keaReply To: isc-projects/keaCc: razvan-becheriu; MentionSubject: Re: [isc-projects/kea] google benchmark support (with lease manager and HDS) (#36)After spending several days improving and fixing the code, it has been finally merged today. There was substantial amount of work (the original diff @razvan-becheriu submitted was 2.4k lines, the changes I did after #issuecomment-359978525 was over 4.8k lines.
The changes are not substantial, there's just a lot of things that had to be done: duplicated code removed, comments added, parameters described, documentation written, methods renamed to be descriptive (how anyone could guest what get6_4() supposed to do?) and follow Kea coding guidelines, code wrapped etc. I understand that these kind of changes may not be the most exciting things to do, but in the future we will not accept patches that require to much of such obvious fixes.
The code is now merged on our internal master. The commits should pop up on github in an hour or so. Thanks for contributing those patches. Closing.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/isc-projects/kea","title":"isc-projects/kea","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/isc-projects/kea"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tomaszmrugalski in #36: After spending several days improving and fixing the code, it has been finally merged today. There was substantial amount of work (the original diff @razvan-becheriu submitted was 2.4k lines, the changes I did after #issuecomment-359978525 was over 4.8k lines.\r\n\r\nThe changes are not substantial, there's just a lot of things that had to be done: duplicated code removed, comments added, parameters described, documentation written, methods renamed to be descriptive (how anyone could guest what get6_4() supposed to do?) and follow Kea coding guidelines, code wrapped etc. I understand that these kind of changes may not be the most exciting things to do, but in the future we will not accept patches that require to much of such obvious fixes.\r\n\r\nThe code is now merged on our internal master. The commits should pop up on github in an hour or so. Thanks for contributing those patches. Closing."}],"action":{"name":"View Pull Request","url":"https://github.com/isc-projects/kea/pull/36#issuecomment-365437249"}}}

**Pull request closed without merging**
