### PR TITLE
Update dhcpdb_create.mysql

### PR DESCRIPTION
**Pull request by xxwolfsrainxx**
fixing " to ' as mysql will throw errors about "

### CODE REVIEW

**Comment by msiodelski** [comment]
So this appears to be an issue when ANSI_QUOTES sql_mode correct?

**Comment by xxwolfsrainxx** [comment]
You are 100% right. I didn't know you can set this per a session. That's awesome. Learn something new everyday. Closing.

**Comment by msiodelski** [comment]
Actually, I am trying to port this change into Kea because the approach
with a single colon does make it more generic.

Marcin Siodelski
ISC

**Comment by xxwolfsrainxx** [comment]
Well I reopened it for discussion. I do think this makes it more generic but you could also put in the docs that when you run the SQL file on the db that they need to set the ANSI_QUOTES sql_mode to single colon. I have no horse in this race personally.

**Comment by msiodelski** [comment]
I think this is more generic because the single quote doesn't change its meaning when you switch to ANSI_QUOTES mode. Whereas, the double quote do change the meaning. So, switching to single quote would make it work both for the ANSI_QUOTES case and when ANSI_QUOTES is not enabled.

Marcin

**Comment by xxwolfsrainxx** [comment]
I agree.

**Comment by tomaszmrugalski** [comment]
I have reviewed the changes on github30 branch in our internal repo. They look good. The code compiles and unit-tests pass (compiled with --with-dhcp-mysql) on Ubuntu 16.04 x64. Looks like it's ready for merge.

**Comment by msiodelski** [comment]
I applied the change and I also had to apply a bunch of additional changes to make unit test work, as well as to make the upgrade scripts adhere to the single quote notation. This turned out to be more complex then I anticipated but it seems to work both with ANSI_QUOTES mode and without it.

This change is now merged.

**Pull request closed without merging**
