### PR TITLE
Gcc11 build fixes

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Review by fxdupont — COMMENTED** [review]
I understand the memory for std::shared_ptr but not the limits in exceptions.h. Now it does not really matter i.e. I'd just like to understand.

**Comment by kraj** [comment]
> I understand the memory for std::shared_ptr but not the limits in exceptions.h. Now it does not really matter i.e. I'd just like to understand.

yeah I should have fixed the .c files but was lazy uploaded a v2.

**Comment by fxdupont** [comment]
Do you mean that you added the limits header because it is almost included everywhere instead of adding it where it missed? It is not a good practice, I suggest you give the list of .cc files where it should be added or the system and compiler which gave warnings / errors so we can reproduce this and eventually add the setup in the CI.

BTW the real "included everywhere" header is config.h. I know some software using it for commonly used headers (system includes e.g. limits and STL e.g. string) but it was not the choice done for Kea.

**Comment by kraj** [comment]
we dont need it everywhere, it was just 2 sources where it was needed check the new patch I just uploaded.

**Comment by fxdupont** [comment]
I prefer this last version. BTW I put here a reference about climits vs limits headers (limits should be used) for my colleagues:
https://stackoverflow.com/questions/43888950/what-is-the-difference-between-climits-and-limits-header-files-in-c

**Comment by kraj** [comment]
ping~1

**Comment by tomaszmrugalski** [comment]
Thanks for the ping, @kraj. We don't monitor github and our primary platform is ISC hosted gitlab. I've created [kea#1839](https://gitlab.isc.org/isc-projects/kea/-/issues/1839) to make sure that stays on our radars. This is small enough, so I hope to merge it very soon.

**Comment by tomaszmrugalski** [comment]
@kraj, we maintain a list of contributors in the AUTHORS file. How would you like to be credited? Does Khem Raj sound ok? Do you want any affiliation added? Remaining anonymous is also an option if you choose that path.

**Comment by kraj** [comment]
> @kraj, we maintain a list of contributors in the AUTHORS file. How would you like to be credited? Does Khem Raj sound ok? Do you want any affiliation added? Remaining anonymous is also an option if you choose that path.

Khem Raj is Just fine.

**Comment by tomaszmrugalski** [comment]
This is now on master. I've rebased it, which apparently got github confused. The changes went in 38f6f6272f1060036a7bae5d85d1ff7f080628fd and d505f7a7d6fac1c00a4467dfcf1e84f2db508bc6, both properly attributed to @kraj.

Thanks for the patch!

**Pull request closed without merging**
